In [197]:
import sympy as sp
import numpy as np
from sympy import pprint,simplify, expand


# Define symbolic variables
m, psi_n1, psi_n1_bar, psi_n2, psi_n2_bar, psi_n3, psi_n3_bar, t = sp.symbols('m psi_n1 psi_n1_bar psi_n2 psi_n2_bar psi_n3 psi_n3_bar t')
m, t = sp.symbols('m t', real=True)
eps=sp.Symbol('ε', real=True)
# Define the symbolic expressions for theta, phi, and phi_1

# Define the 4x4 rotation matrix R
H = sp.Matrix([[m, 0, 0, eps, 0, eps],
               [0, m, eps, 0, eps, 0],
               [0, eps, m, 0, 0, eps],
               [eps, 0, 0, m, eps, 0],
               [0, eps, 0,eps,m,0],
               [eps, 0, eps, 0, 0,m]])
I=sp.Matrix([[1, 0, 0, 0, 0, 0],
            [0, 1, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 1]])

# Define the 4x4 matrix P

In [198]:
H

Matrix([
[m, 0, 0, ε, 0, ε],
[0, m, ε, 0, ε, 0],
[0, ε, m, 0, 0, ε],
[ε, 0, 0, m, ε, 0],
[0, ε, 0, ε, m, 0],
[ε, 0, ε, 0, 0, m]])

In [199]:
H@H

Matrix([
[m**2 + 2*ε**2,             0,          ε**2,         2*m*ε,          ε**2,         2*m*ε],
[            0, m**2 + 2*ε**2,         2*m*ε,          ε**2,         2*m*ε,          ε**2],
[         ε**2,         2*m*ε, m**2 + 2*ε**2,             0,          ε**2,         2*m*ε],
[        2*m*ε,          ε**2,             0, m**2 + 2*ε**2,         2*m*ε,          ε**2],
[         ε**2,         2*m*ε,          ε**2,         2*m*ε, m**2 + 2*ε**2,             0],
[        2*m*ε,          ε**2,         2*m*ε,          ε**2,             0, m**2 + 2*ε**2]])

In [200]:
H@H@H

Matrix([
[       4*m*ε**2 + m*(m**2 + 2*ε**2),                              2*ε**3,                            3*m*ε**2, 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),                            3*m*ε**2, 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2)],
[                             2*ε**3,        4*m*ε**2 + m*(m**2 + 2*ε**2), 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),                            3*m*ε**2, 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),                            3*m*ε**2],
[                           3*m*ε**2, 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),        4*m*ε**2 + m*(m**2 + 2*ε**2),                              2*ε**3,                            3*m*ε**2, 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2)],
[2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),                            3*m*ε**2,                              2*ε**3,        4*m*ε**2 + m*(m**2 + 2*ε**2), 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),                            3*m*ε**2],
[                           3*m*ε**2, 2*m**2*ε + ε**3 + ε*(m**2 + 2*ε**2),                     

In [201]:
psi_n1=sp.Matrix([[1], [0],[0],[0],[0],[0]])
psi_n1_bar=sp.Matrix([[0, 1, 0, 0, 0, 0]])
psi_n2=sp.Matrix([[0], [0],[1],[0],[0],[0]])
psi_n2_bar=sp.Matrix([[0, 0, 0, 1, 0, 0]])
psi_n3=sp.Matrix([[0], [0],[0],[0],[1],[0]])
psi_n3_bar=sp.Matrix([[0, 0, 0, 0, 0, 1]])

In [230]:
#Order 1

S=I-sp.I*H*t

In [203]:
S=sp.nsimplify(S)

In [204]:
S

Matrix([
[-I*m*t + 1,          0,          0,     -I*t*ε,          0,     -I*t*ε],
[         0, -I*m*t + 1,     -I*t*ε,          0,     -I*t*ε,          0],
[         0,     -I*t*ε, -I*m*t + 1,          0,          0,     -I*t*ε],
[    -I*t*ε,          0,          0, -I*m*t + 1,     -I*t*ε,          0],
[         0,     -I*t*ε,          0,     -I*t*ε, -I*m*t + 1,          0],
[    -I*t*ε,          0,     -I*t*ε,          0,          0, -I*m*t + 1]])

In [205]:
expr_11=sp.Matrix([[1, 0, 0, 0, 0, 0]])@S@psi_n1
#scalar_11=expr_11[0,0]
M_11=(expr_11.H@expr_11)[0,0]

expr_1b1=psi_n1_bar@S@psi_n1
scalar_1b1=expr_1b1[0,0]
M_1b1=(expr_1b1.H@expr_1b1)[0,0]

expr_21=sp.Matrix([[0, 0, 1, 0, 0, 0]])@S@psi_n1
scalar_21=expr_21[0,0]
M_21=(expr_21.H@expr_21)[0,0]

expr_2b1=psi_n2_bar@S@psi_n1
scalar_2b1=expr_2b1[0,0]
M_2b1=(expr_2b1.H@expr_2b1)[0,0]

expr_31=sp.Matrix([[0, 0, 0, 0, 1, 0]])@S@psi_n1
scalar_31=expr_31[0,0]
M_31=(expr_31.H@expr_31)[0,0]

expr_3b1=psi_n3_bar@S@psi_n1
scalar_3b1=expr_3b1[0,0]
M_3b1=(expr_3b1.H@expr_3b1)[0,0]

In [289]:
#expr_1b1
pprint(psi_n1)
pprint(psi_n1_bar)
pprint(psi_n2)
pprint(psi_n2_bar)
pprint(psi_n3)
pprint(psi_n3_bar)

⎡1⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦
[0  1  0  0  0  0]
⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢1⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦
[0  0  0  1  0  0]
⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣0⎦
[0  0  0  0  0  1]


In [291]:
psi_n1_bar@S@psi_n1

Matrix([[0]])

In [226]:
M_11str = str(sp.simplify(M_11)).replace("**2", "²").replace("*", "")
M_1b1str = str(sp.simplify(M_1b1)).replace("**2", "²").replace("*", "")

M_21str = str(sp.simplify(M_21)).replace("**2", "²").replace("*", "")
M_2b1str = str(sp.simplify(M_2b1)).replace("**2", "²").replace("*", "")

M_31str = str(sp.simplify(M_31)).replace("**2", "²").replace("*", "")
M_3b1str = str(sp.simplify(M_3b1)).replace("**2", "²").replace("*", "")

In [228]:
#P=psi_n1_bar@S@psi_n1
expr_str = str(expr).replace("**2", "²").replace("*", "")
print("P(n₁ → n₁)= ", M_11str)
print("P(n̄₁ → n₁)= ", M_1b1str)
print("P(n₂ → n₁)= ", M_21str)
print("P(n̄₂ → n₁)= ", M_2b1str)
print("P(n₃ → n₁)= ", M_31str)
print("P(n̄₃ → n₁)= ", M_3b1str)


P(n₁ → n₁)=  m²t² + 1
P(n̄₁ → n₁)=  0
P(n₂ → n₁)=  0
P(n̄₂ → n₁)=  t²ε²
P(n₃ → n₁)=  0
P(n̄₃ → n₁)=  t²ε²


In [208]:
#P

In [214]:
#Order 2

In [255]:
S_2=I-sp.I*H*t-1/2*(H@H)*t**2


In [263]:
expr2_11=sp.Matrix([[1, 0, 0, 0, 0, 0]])@S_2@psi_n1
#scalar_11=expr_11[0,0]
M2_11=(expr2_11.H@expr2_11)[0,0]

expr2_1b1=psi_n1_bar@S_2@psi_n1
scalar2_1b1=expr_1b1[0,0]
M2_1b1=(expr2_1b1.H@expr2_1b1)[0,0]

expr2_21=sp.Matrix([[0, 0, 1, 0, 0, 0]])@S_2@psi_n1
scalar2_21=expr_21[0,0]
M2_21=(expr2_21.H@expr2_21)[0,0]

expr2_2b1=psi_n2_bar@S_2@psi_n1
scalar2_2b1=expr_2b1[0,0]
M2_2b1=(expr2_2b1.H@expr2_2b1)[0,0]

expr2_31=sp.Matrix([[0, 0, 0, 0, 1, 0]])@S_2@psi_n1
scalar2_31=expr_31[0,0]
M2_31=(expr2_31.H@expr2_31)[0,0]

expr2_3b1=psi_n3_bar@S_2@psi_n1
scalar2_3b1=expr_3b1[0,0]
M2_3b1=(expr2_3b1.H@expr2_3b1)[0,0]

In [352]:
#expr_1b1
#psi_n1_bar@S_2

In [355]:
M2_11str = str(sp.simplify(M2_11, rational=True)).replace("**2", "²").replace("*", "")
M2_1b1str = str(sp.simplify(M2_1b1, rational=True)).replace("**2", "²").replace("*", "")

M2_21str = str(sp.simplify(M2_21, rational=True)).replace("**2", "²").replace("*", "")
M2_2b1str = str(sp.simplify(M2_2b1, rational=True)).replace("**2", "²").replace("*", "")

M2_31str = str(sp.simplify(M2_31, rational=True)).replace("**2", "²").replace("*", "")
M2_3b1str = str(sp.simplify(M2_3b1, rational=True)).replace("**2", "²").replace("*", "")

In [356]:
print("P(n₁ → n₁)= ", M2_11str)
print("P(n̄₁ → n₁)= ", M2_1b1str)
print("P(n₂ → n₁)= ", M2_21str)
print("P(n̄₂ → n₁)= ", M2_2b1str)
print("P(n₃ → n₁)= ", M2_31str)
print("P(n̄₃ → n₁)= ", M2_3b1str)

P(n₁ → n₁)=  m4t4/4 + m²t4ε² + t4ε4 - 2t²ε² + 1
P(n̄₁ → n₁)=  0
P(n₂ → n₁)=  t4ε4/4
P(n̄₂ → n₁)=  t²ε²(m²t² + 1)
P(n₃ → n₁)=  t4ε4/4
P(n̄₃ → n₁)=  t²ε²(m²t² + 1)


In [ ]:
#Order 3

In [276]:
S_3=I-sp.I*H*t-1/2*(H@H)*t**2-sp.I/6*(H@H@H)*t**3

In [308]:
expr3_11=sp.Matrix([[1, 0, 0, 0, 0, 0]])@S_3@psi_n1
#scalar_11=expr_11[0,0]
M3_11=(expr3_11.H@expr3_11)[0,0]

expr3_1b1=psi_n1_bar@S_3@psi_n1
scalar3_1b1=expr3_1b1[0,0]
M3_1b1=(expr3_1b1.H@expr3_1b1)[0,0]

expr3_21=sp.Matrix([[0, 0, 1, 0, 0, 0]])@S_3@psi_n1
scalar3_21=expr3_21[0,0]
M3_21=(expr3_21.H@expr3_21)[0,0]

expr3_2b1=psi_n2_bar@S_3@psi_n1
scalar3_2b1=expr3_2b1[0,0]
M3_2b1=(expr3_2b1.H@expr3_2b1)[0,0]

expr3_31=sp.Matrix([[0, 0, 0, 0, 1, 0]])@S_3@psi_n1
scalar3_31=expr3_31[0,0]
M3_31=(expr3_31.H@expr3_31)[0,0]

expr3_3b1=psi_n3_bar@S_3@psi_n1
scalar3_3b1=expr3_3b1[0,0]
M3_3b1=(expr3_3b1.H@expr3_3b1)[0,0]

In [309]:
expr_1b1
M3_1b1

t**6*ε**6/9

In [310]:
psi_n1_bar@S_3@psi_n1

Matrix([[-I*t**3*ε**3/3]])

In [328]:
M3_11c = sp.nsimplify(sp.simplify(M3_11), rational=True)
M3_1b1c = sp.nsimplify(sp.simplify(M3_1b1), rational=True)
M3_21c = sp.nsimplify(sp.simplify(M3_21), rational=True)
M3_2b1c = sp.nsimplify(sp.simplify(M3_2b1), rational=True)
M3_31c = sp.nsimplify(sp.simplify(M3_31), rational=True)
M3_3b1c = sp.nsimplify(sp.simplify(M3_3b1), rational=True)

In [335]:
def pretty(expr):
    expr = str(expr)
    return (expr
        .replace("**6", "⁶")
        .replace("**5", "⁵")
        .replace("**4", "⁴")
        .replace("**3", "³")
        .replace("**2", "²")
        .replace("*", "")
    )

In [350]:
M3_11str = pretty(sp.expand(sp.simplify(M3_11, rational=True)))
M3_1b1str = pretty(sp.expand(sp.simplify(M3_1b1, rational=True)))

M3_21str = pretty(sp.expand(sp.simplify(M3_21, rational=True)))
M3_2b1str = pretty(sp.expand(sp.simplify(M3_2b1, rational=True)))

M3_31str = pretty(sp.expand(sp.simplify(M3_31, rational=True)))
M3_3b1str = pretty(sp.expand(sp.simplify(M3_3b1, rational=True)))

In [351]:
print("P(n₁ → n₁)= ", M3_11str)
print("P(n̄₁ → n₁)= ", M3_1b1str)
print("P(n₂ → n₁)= ", M3_21str)
print("P(n̄₂ → n₁)= ", M3_2b1str)
print("P(n₃ → n₁)= ", M3_31str)
print("P(n̄₃ → n₁)= ", M3_3b1str)

P(n₁ → n₁)=  m⁶t⁶/36 + m⁴t⁶ε²/3 + 7m⁴t⁴/12 + m²t⁶ε⁴ + 3m²t⁴ε² + t⁴ε⁴ - 2t²ε² + 1
P(n̄₁ → n₁)=  t⁶ε⁶/9
P(n₂ → n₁)=  m²t⁶ε⁴/4 + t⁴ε⁴/4
P(n̄₂ → n₁)=  m⁴t⁶ε²/4 + m²t⁶ε⁴/2 + 2m²t⁴ε² + t⁶ε⁶/4 + t⁴ε⁴ + t²ε²
P(n₃ → n₁)=  m²t⁶ε⁴/4 + t⁴ε⁴/4
P(n̄₃ → n₁)=  m⁴t⁶ε²/4 + m²t⁶ε⁴/2 + 2m²t⁴ε² + t⁶ε⁶/4 + t⁴ε⁴ + t²ε²


In [341]:
#a=sp.nsimplify(sp.simplify(M3_11), rational=True)

In [346]:

#a